name: Build and deploy ASP.Net Core microservice to Azure Web App - Web-Api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build RabbitMQ Service
        run: dotnet build ./RabbitMQ/RabbitMQ.sln --configuration Release

      - name: Build ReceiverRabbitMQ Service
        run: dotnet build ./ReceiverRabbitMQ/ReceiverRabbitMQ.sln --configuration Release

      - name: Publish ReceiverRabbitMQ for deployment
        run: dotnet publish ./ReceiverRabbitMQ/ReceiverRabbitMQ/ReceiverRabbitMQ.csproj --configuration Release --output '${{env.DOTNET_ROOT}}/receiverapp'

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: receiver-app
          path: ${{env.DOTNET_ROOT}}/receiverapp

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: receiver-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Web-Api' # change this to your app name
          slot-name: 'Production'
          package: .
