name: Build and deploy ASP.Net Core app to Azure Web App - Web-Api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build ./src/WebApiApp/WebApiApp.csproj --configuration Release

      - name: dotnet publish
        run: dotnet publish ./src/WebApiApp/WebApiApp.csproj --configuration Release --output '${{env.DOTNET_ROOT}}/myapp'

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2518E586ED924FD48F8CEFE2CB15E35E }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C9663E55B3924543B0CC629EA9477A05 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7103598665C74484AD9A8AB549540A2B }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Web-Api'
          slot-name: 'Production'
          package: .
